#!/bin/sh
cd src
ghc Main.hs --make -package wx -o ../bin/hPage -odir ../out -hidir ../out $1 $2 $3
cd ../bin
/usr/local/wxhaskell/bin/macosx-app hPage
cd hPage.app/Contents/MacOS/
./hPage &
cd ../../..
