
module Graphics.UI.WXCore.WxcDefs.ExtraIdentities where

wxID_REPLACE, wxID_REPLACE_ALL, wxID_PREFERENCES,
    wxID_CLOSE_ALL :: Int
wxID_REPLACE        = 5038
wxID_REPLACE_ALL    = 5039
wxID_PREFERENCES    = 5022
wxID_CLOSE_ALL      = 5018

wxID_HASK_LOAD, wxID_HASK_LOADNAME, wxID_HASK_RELOAD,
    wxID_HASK_VALUE, wxID_HASK_TYPE, wxID_HASK_KIND,
    wxID_HASK_ADD :: Int
wxID_HASK_LOAD      = 5300
wxID_HASK_LOADNAME  = 5301
wxID_HASK_RELOAD    = 5302
wxID_HASK_VALUE     = 5304
wxID_HASK_TYPE      = 5305
wxID_HASK_KIND      = 5306
wxID_HASK_ADD       = 5307